-- MySQL Script generated by MySQL Workbench
-- Mon 09 Jun 2014 11:28:30 AM MDT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema diyauto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diyauto` DEFAULT CHARACTER SET latin1 ;
USE `diyauto` ;

-- -----------------------------------------------------
-- Table `diyauto`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diyauto`.`Account` ;

CREATE TABLE IF NOT EXISTS `diyauto`.`Account` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `PassWord` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(80) NOT NULL,
  `Avatar` VARCHAR(255) NOT NULL DEFAULT 'Something',
  `username` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diyauto`.`AccountRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diyauto`.`AccountRole` ;

CREATE TABLE IF NOT EXISTS `diyauto`.`AccountRole` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserId` INT(11) NOT NULL,
  `Role` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `UserId` (`UserId` ASC),
  CONSTRAINT `AccountRole_ibfk_1`
    FOREIGN KEY (`UserId`)
    REFERENCES `diyauto`.`Account` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diyauto`.`Make`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diyauto`.`Make` ;

CREATE TABLE IF NOT EXISTS `diyauto`.`Make` (
  `idMake` INT(11) NOT NULL AUTO_INCREMENT,
  `Make` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMake`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diyauto`.`Model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diyauto`.`Model` ;

CREATE TABLE IF NOT EXISTS `diyauto`.`Model` (
  `idModel` INT(11) NOT NULL AUTO_INCREMENT,
  `Model` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idModel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diyauto`.`SubModel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diyauto`.`SubModel` ;

CREATE TABLE IF NOT EXISTS `diyauto`.`SubModel` (
  `idSubModel` INT(11) NOT NULL AUTO_INCREMENT,
  `SubModel` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idSubModel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diyauto`.`Cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diyauto`.`Cars` ;

CREATE TABLE IF NOT EXISTS `diyauto`.`Cars` (
  `idCars` INT(11) NOT NULL AUTO_INCREMENT,
  `MakeID` INT(11) NOT NULL,
  `ModelID` INT(11) NOT NULL,
  `SubModelID` INT(11) NOT NULL,
  `Year` YEAR NOT NULL,
  `UserID` INT(11) NOT NULL,
  PRIMARY KEY (`idCars`),
  INDEX `MakeID` (`MakeID` ASC),
  INDEX `ModelID` (`ModelID` ASC),
  INDEX `SubModelID` (`SubModelID` ASC),
  INDEX `UserID` (`UserID` ASC),
  CONSTRAINT `Cars_ibfk_1`
    FOREIGN KEY (`MakeID`)
    REFERENCES `diyauto`.`Make` (`idMake`),
  CONSTRAINT `Cars_ibfk_2`
    FOREIGN KEY (`ModelID`)
    REFERENCES `diyauto`.`Model` (`idModel`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Cars_ibfk_3`
    FOREIGN KEY (`SubModelID`)
    REFERENCES `diyauto`.`SubModel` (`idSubModel`),
  CONSTRAINT `Cars_ibfk_4`
    FOREIGN KEY (`UserID`)
    REFERENCES `diyauto`.`Account` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '		';


-- -----------------------------------------------------
-- Table `diyauto`.`Threads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diyauto`.`Threads` ;

CREATE TABLE IF NOT EXISTS `diyauto`.`Threads` (
  `idThreads` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idThreads`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diyauto`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diyauto`.`Post` ;

CREATE TABLE IF NOT EXISTS `diyauto`.`Post` (
  `idPost` INT(11) NOT NULL AUTO_INCREMENT,
  `UserID` INT(11) NOT NULL,
  `Description` TEXT NOT NULL,
  `Title` VARCHAR(50) NOT NULL,
  `threadId` INT NOT NULL,
  PRIMARY KEY (`idPost`),
  INDEX `UserID` (`UserID` ASC),
  INDEX `Thread_Post_1_idx` (`threadId` ASC),
  CONSTRAINT `Post_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `diyauto`.`Account` (`idUser`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Thread_Post_1`
    FOREIGN KEY (`threadId`)
    REFERENCES `diyauto`.`Threads` (`idThreads`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diyauto`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diyauto`.`Comment` ;

CREATE TABLE IF NOT EXISTS `diyauto`.`Comment` (
  `idComment` INT(11) NOT NULL AUTO_INCREMENT,
  `Comment` TEXT NOT NULL,
  `UserID` INT(11) NOT NULL,
  `postId` INT NOT NULL,
  PRIMARY KEY (`idComment`),
  INDEX `UserID` (`UserID` ASC),
  INDEX `Post_Comment_1_idx` (`postId` ASC),
  CONSTRAINT `Comment_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `diyauto`.`Account` (`idUser`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Post_Comment_1`
    FOREIGN KEY (`postId`)
    REFERENCES `diyauto`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `diyauto`.`Account`
-- -----------------------------------------------------
START TRANSACTION;
USE `diyauto`;
INSERT INTO `diyauto`.`Account` (`idUser`, `PassWord`, `Email`, `Avatar`, `username`) VALUES (NULL, 'stuff', 'stuff@stuff.com', '', 'Stuffington');

COMMIT;


-- -----------------------------------------------------
-- Data for table `diyauto`.`Threads`
-- -----------------------------------------------------
START TRANSACTION;
USE `diyauto`;
INSERT INTO `diyauto`.`Threads` (`idThreads`, `Name`, `Description`) VALUES (NULL, 'TestThread', 'Testing data.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `diyauto`.`Post`
-- -----------------------------------------------------
START TRANSACTION;
USE `diyauto`;
INSERT INTO `diyauto`.`Post` (`idPost`, `UserID`, `Description`, `Title`, `threadId`) VALUES (NULL, 1, 'Popped tire', 'Wheel Blew Out', 1);

COMMIT;

